DELETE http://localhost:3001/api/persons/2 HTTP/1.1

###
GET http://localhost:3001/api/persons/ HTTP/1.1

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Carlos",
    "number": "84648955579"
}